name: send email

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Send email
    uses: dawidd6/action-send-mail@v3
    with:
      server_address: smtp.gmail.com
      server_port: 465

      username: ${{ secrets.MAIL_USERNAME }}
      password: ${{ secrets.MAIL_PASSWORD }}

      subject: Github Actions job result
      to: andrew.beet@noaa.gov

      from: Luke Skywalker # OR 'Luke Skywalker <user@example.com>'

      body: Build job of ${{ github.repository }} completed successfully!
