name: pull and process data from stocksmart website

on:
  push:
#    branches:
#      - dev2 # this doesnt exist

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_RELEASE }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install command line packages
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
#          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install packages
        run: |
          install.packages(c("usethis","here"))
          version <- NULL
          saveRDS(version,here::here("data-raw/version.rds"))
        shell: Rscript {0}

      - name: create gh-release
        run: |
            version <- readRDS(here::here("data-raw/version.rds"))
            if(!is.null(version)){
            usethis::use_github_release(publish = F)
            }
        shell: Rscript {0}



