name: pull and process data from stocksmart website

on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install command line packages
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
#          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install packages
        run: |
          install.packages(c("dplyr", "httr", "here","readxl", "usethis","rmarkdown"))
        shell: Rscript {0}

      - name: Save current rdas
        run: |
           saveRDS(here::here("data/stockAssessmentSummary.rda),here::here("data-raw/tempSummary.rds"))
           saveRDS(here::here("data/stockAssessmentData.rda"),here::here("data-raw/tempData.rds"))
        shell: Rscript{0}


#       - name: Check for differences between data pull & existing
      # If same then need to exit without commit

      #- name: Find differences
      # Create text explaining differences and append to news.md and release notes

      - name: Send email
        uses: dawidd6/action-send-mail@v3

        with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: Github Actions job result
          to: andrew.beet@noaa.gov

          from: Luke Skywalker # OR 'Luke Skywalker <user@example.com>'

          body: ${{ github.repository }} updated data!

          #html_body: file://${{github.workspace}}/data-raw/sendAsEmail.html

      - name: commit data files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/stockAssessmentData.rda
          git add data/stockAssessmentSummary.rda
          git add data-raw/datapull.txt
          git add data-raw/Assessment_Summary_Data.xlsx
          git add README.md
          git commit -m "automated commit from api yml"
          git push



#       - name: Autoincrement a new patch version
      #   run: |
      #     echo "NEW_PATCH_VERSION=$((${{ env.PATCH_VERSION }}+1))" >> $GITHUB_ENV
      # - name: Update patch version
      #   uses: hmanzur/actions-set-secret@v2.0.0
      #   with:
      #     name: 'PATCH_VERSION'
      #     value: ${{ env.NEW_PATCH_VERSION }}
      #     repository: ${{ github.repository }}
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
